### ISSUE TITLE
ardb and memory use

### ISSUE THREAD

**Issue by amnond** [yinqiwen/ardb#178]
I've been running some tests on ardb vs. redis and I've noticed that ardb (with the default rocksdb) consumes much more memory than redis does - sometimes an order of magnitude more. As ardb was meant to give an alternative to redis RAM consumption, it is obvious I'm doing something wrong.

The test I run is the following simple Python script:
```python
import redis
from timeit import default_timer as timer

r1 = redis.StrictRedis(host='localhost', port=16379, db=0) # ardb
r2 = redis.StrictRedis(host='localhost', port=6379, db=0) # redis
r1.flushall()
r2.flushall()
loops = 5000

print('redis lpush:')
start = timer()
for i in range(1,50):
    for l in range(1,loops):
        lkey = 'list_'+str(l)
        val = 'val-'+str(i-1)
        r2.lpush(lkey, val)
end = timer()
print(end-start)

print('ardb lpush:')
start = timer()
for i in range(1,50):
    for l in range(1,loops):
        lkey = 'list_'+str(l)
        val = 'val-'+str(i-1)
        r1.lpush(lkey, val)
end = timer()
print(end-start)
```
If the ardb-server is stopped and restarted, the memory goes back to logical values (and I can access the stored data). Any suggestions on how to avoid the huge memory consumption or at least reclaim memory without restarting the ardb server? Is this related to rocksdb parameters in ardb.conf?

**Comment by limbo127** [comment]
hello, 
I've the same issus with LMDB, ardb memory is growing, LMDB is using mapped memory file, so il should not be consume so much memory.
Regards,

**Comment by yinqiwen** [comment]
u can estimate Rocksdb/leveldb's  max memory usage by the way described in the `Readme`. 

    write_buffer_size*2    + max_open_files*4194304   + (size in NewLRUCache initialization)

**Comment by antony66** [comment]
I can confirm I've got the same memory usage issue with leveldb and rocksdb. I tried to use ardb as a cache instead of redis. All the values I put in ardb have ttl set so they should disappear automatically. Having approx. 100-1500 key/value pairs in ardb my ardb-server process slowly grows up to 10GB of virtual memory, then I restart it. With original redis and the same usage pattern my redis takes less than 1GB memory.

**Comment by antony66** [comment]
Ahh wait. Is it ok that default ardb.conf contains:

    # Enable compact GC task or not
    compact-enable  no

and can it cause the issue?

**Comment by yinqiwen** [comment]
the options is only used for leveldb/rocksdb

**Comment by antony66** [comment]
I only used leveldb and rocksdb backends. With rocksdb it could grow up to 20 gb virtual ram.

Yesterday I enabled compacting with leveldb and it did compacting every hour according to logs. 2 things happened:

1. Process grew up to 2.5 gb by this morning having only 1000 images less than 1 gb each (I use ardb/redis as srcache backend to my nginx)
2. It started to drop random keys or commands. SRCache sends "set ..." command and just after 1-2 seconds after that corresponding key disappears from ardb. SRCache does not remove anything from cache. It's completely up to cache backend to purge expired items. I use "expire ..." for it. My TTL for SRCache is configured to 15 minutes. 

Now I switched back to redis 2.8 (debian wheezy backports edition). Redis process takes 80 mb memory holding 850 keys (images)

**Comment by antony66** [comment]
I wrote "SRCache sends set .." because I actually monitored traffic on my 127.0.0.1:6379 and saw those commands and replies from ardb confirming those keys were set. Then I run a few "get ..." commands in a row and after a couple of seconds the key just disappeared.

When I switch back to redis it never happens with the same app.

**Comment by yinqiwen** [comment]
for complex value(list/hash/zset/set), ardb would use more space than redis. Because the storage engine only support simple key-value, there is a virtual encode/decode layer over the storage engine which would use more space.

and leveldb/rocksdb is append-only for all write/delete operations, if the app continue modify the same key many times, leveldb/rocksdb would use more space before it compacted all data.

**Comment by antony66** [comment]
SRCache (it's nginx's cache) only uses GET/SET and EXPIRE commands, no lists/hashes. The app (this is just a cache) never modifies existing keys. They got expired, then it may create a new key with the same name and value.

**Comment by yinqiwen** [comment]
Is the memory RSS footprint finally stop increasing? 
In our production env, ardb use about 44G rss memory for serving 153G data(disk usage), while the ardb instance enabled the LRU cache.
![image](https://cloud.githubusercontent.com/assets/222799/7878721/feeddb02-061b-11e5-9f22-56dcc2672283.png)

**Comment by antony66** [comment]
I am not sure because my host is limited to 24 Gb and when ardb grows that big OS invokes OOM killer. But I hever had over 10 Gb on disk. Even less.

**Comment by yinqiwen** [comment]
is the code latest? seems there is a memory leak

**Comment by antony66** [comment]
commit be8a48a1e07ab202d9713a4f68298e022fbb5285
    Date:   Wed Apr 29 10:38:37 2015 +0800

**Comment by antony66** [comment]
L1 cache is disabled

**Comment by antony66** [comment]
```
leveldb.block_cache_size       512m
leveldb.block_size             0
leveldb.write_buffer_size      128m
leveldb.block_restart_interval 0
leveldb.max_open_files         1024
leveldb.bloom_bits             10
leveldb.batch_commit_watermark 1024
# Specify the leveldb's compression
# This can be one of snappy/none
leveldb.compression            snappy
```

compiled on Debian Wheezy

**Comment by haneefmubarak** [comment]
Might this be related to #126?
