### ISSUE TITLE
ardb/leveldb and flushall

### ISSUE THREAD

**Issue by bdfy** [yinqiwen/ardb#235]
I create levelDB, but flushall not working. After flushall size of database not trunkated, 
keys * run 10 seconds, but return empty results. Why ?

**Comment by yinqiwen** [comment]
for leveldb/rocksdb and other storage engine which build by lsm tree, put/delete operations are just like  append operations, which means that if you continue put/delete same key, the disk space use by ardb would continue increase until the background compact task decided to merge them.

flushall is an operation that iterate all keys and delete it, keys * is an operation that iterate all keys and check it it be deleted,  that's why it's so slow. If u 'compactall' before "keys *", it would be much faster.

**Comment by yinqiwen** [comment]
Anyway,for this issue ,there is a simple fix to make "keys *" return  faster after "flushall" just committed.
