### ISSUE TITLE
Does not recover from "No space left on device" error

### ISSUE THREAD

**Issue by maros** [yinqiwen/ardb#310]
I just ran into an issue where ardb would not recover from a "No space left on device" error. To reproduce the error:

- Fill the volume where ardb is running
- Add a key. This results in a "No space left on device" error
- Clean the volume
- Add another key. This still results in a "No space left on device" error, even there is now plenty of free space. Only restart of ardb helped in this situation

Thank you

**Comment by yinqiwen** [comment]
this is an known issue for rocksdb https://github.com/facebook/rocksdb/issues/919, currently the only way is to restart db server.

**Comment by rafalsk** [comment]
bump-up for this issue; we've got quite a behemoth app built-in top of RocksDB.. we've accounted for such a situation(user running of of space); still today; during testing it turned out that RocksDB itself would not recover.. and now; reseting the db server would require some considerable refactoring...
